In [1]:
import numpy as np

In [7]:
s = np.array(5)
print(s)
print('=============')
v = np.array([1,2,3])
print(v)
print('=============')
m = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(m.ndim)

5
[1 2 3]
2


In [10]:
vec1 = np.array([1,2,3,4,5,6])
mat1 = vec1.reshape((3,2))
print(mat1)

[[1 2]
 [3 4]
 [5 6]]


In [25]:
vec2 = np.array([1,2,3,4])
mat2 = vec2.reshape((vec2.shape[0], 1))
print(mat2)
vec2.shape[0]

[[1]
 [2]
 [3]
 [4]]


4

In [29]:
vec2[:,None]

array([[1],
       [2],
       [3],
       [4]])

In [33]:
image = r'C:\Users\Maydoum\OneDrive\Desktop\DEPI\projects\Depi_Amit_AI_BNS3\sources\session_work\img.png'
vec2 = np.array(image)
mat2 = vec2.reshape(vec2.shape[0], 1)

IndexError: tuple index out of range

In [38]:
mat = np.array([
    [1,True,3.2],
    [4,5,6],
    [7,8,9]
])
mat.dtype

dtype('float64')

In [ ]:
vec1 = np.array([1,2,3,4,5,6])
vec1[-1]

np.int64(6)

In [50]:
mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [0,0,0]
])
mat[1,-2]
mat[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [51]:
transpose = mat.T
transpose

array([[1, 4, 7, 0],
       [2, 5, 8, 0],
       [3, 6, 9, 0]])

In [56]:
mat = np.zeros((3,4))
print(mat)
print(mat.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [60]:
mat = np.identity(3,dtype='float32')
mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [61]:
mat = np.full((3,3),5)
mat

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [62]:
angle = np.arange(0,361,90)
angle

array([  0,  90, 180, 270, 360])

In [63]:
def rotate_img(angle):
    return

In [ ]:
np.random.random((3,3))
np.random.randint(0,11,(3,3))


array([[ 2, 10,  5],
       [ 6,  0,  1],
       [ 2,  2,  6]], dtype=int32)

In [83]:
a = ['ali',10,'amir',True]
np.random.choice(a,size=(3,5))

array([['amir', '10', 'True', 'amir', 'True'],
       ['amir', '10', 'amir', 'ali', '10'],
       ['amir', 'ali', '10', 'True', 'ali']], dtype='<U21')